[package]
name = "azc-rust"
version = "0.1.0"
authors = ["Fahrezal Effendi <exavolt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mopa = "0.2"
num = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
